name: Create PR from dev to main

on:
  push:
    branches:
      - dev

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          gh pr create --base main --head dev --title "Merge dev into main" --body "Automatic PR from dev push" --repo ${{ github.repository }}
