name: Create PR from dev to main

on:
  push:
    branches:
      - dev

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install ripgrep
        run: |
          curl -LO https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
          sudo dpkg -i ripgrep_13.0.0_amd64.deb
        shell: bash

      - name: Create PR and Get PR URL
        id: create_pr
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          PR_URL=$(gh pr create --base main --head dev --title "Merge dev into main" --body "Automatic PR from dev push" --label "Don't Merge" --repo ${{ github.repository }})
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
        shell: bash
  
      - name: Extract PR Number
        id: extract_pr_number
        run: |
          PR_URL="${{ steps.create_pr.outputs.pr_url }}"
          PR_NUMBER=$(echo "$PR_URL" | rg -o 'https://github\.com/.+/pull/(\d+)' --replace '$1')
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT

        shell: bash
  
      - name: Assign Milestone to PR
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          PR_NUMBER="${{ steps.create_pr.outputs.pr_number }}"
          gh pr edit $PR_NUMBER --milestone 1
